
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.text.DateFormat;
import java.text.MessageFormat;
import java.text.ParseException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Louisa
 */
public class form_pembayaran extends javax.swing.JFrame {
        String tglpinjam;
        String tglkembali;
    /**
     * Creates new form form_pembayaran
     */
    public form_pembayaran() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labeltanggal = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        labeljam = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        nopol = new javax.swing.JTextField();
        petugas = new javax.swing.JTextField();
        noresi = new javax.swing.JTextField();
        motor = new javax.swing.JRadioButton();
        mobil = new javax.swing.JRadioButton();
        keluar = new com.toedter.calendar.JDateChooser();
        masuk = new com.toedter.calendar.JDateChooser();
        jPanel5 = new javax.swing.JPanel();
        clear = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        print = new javax.swing.JButton();
        refresh = new javax.swing.JButton();
        save = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        akhir = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(930, 50));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setText("PENITIPAN MOTOR DAN MOBIL");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(276, 0, 444, 50);

        labeltanggal.setText("Tanggal");
        jPanel2.add(labeltanggal);
        labeltanggal.setBounds(872, 11, 122, 28);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 1050, 50);

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(930, 50));
        jPanel3.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Viner Hand ITC", 1, 18)); // NOI18N
        jLabel2.setText("LOUISA GABRIELLA CV");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(364, 0, 448, 50);

        labeljam.setText("Jam");
        jPanel3.add(labeljam);
        labeljam.setBounds(873, 17, 122, 14);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 56, 1050, 50);

        jPanel4.setBackground(new java.awt.Color(255, 204, 153));
        jPanel4.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Nama Petugas");
        jPanel4.add(jLabel3);
        jLabel3.setBounds(10, 11, 140, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("No Resi");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(10, 60, 140, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("No Polisi");
        jPanel4.add(jLabel5);
        jLabel5.setBounds(10, 110, 140, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Jenis Kendaraan");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(10, 170, 140, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Tanggal Masuk");
        jPanel4.add(jLabel7);
        jLabel7.setBounds(10, 230, 140, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Tanggal Keluar");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(10, 280, 140, 40);

        nopol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nopolActionPerformed(evt);
            }
        });
        jPanel4.add(nopol);
        nopol.setBounds(160, 110, 230, 40);

        petugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                petugasActionPerformed(evt);
            }
        });
        jPanel4.add(petugas);
        petugas.setBounds(160, 10, 230, 40);
        jPanel4.add(noresi);
        noresi.setBounds(160, 60, 230, 40);

        buttonGroup1.add(motor);
        motor.setText("Motor");
        motor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motorActionPerformed(evt);
            }
        });
        jPanel4.add(motor);
        motor.setBounds(160, 170, 100, 40);

        buttonGroup1.add(mobil);
        mobil.setText("Mobil");
        jPanel4.add(mobil);
        mobil.setBounds(280, 170, 110, 40);

        keluar.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                keluarPropertyChange(evt);
            }
        });
        jPanel4.add(keluar);
        keluar.setBounds(160, 280, 230, 40);

        masuk.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                masukPropertyChange(evt);
            }
        });
        jPanel4.add(masuk);
        masuk.setBounds(160, 230, 230, 40);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(10, 120, 400, 330);

        jPanel5.setBackground(new java.awt.Color(255, 204, 153));
        jPanel5.setPreferredSize(new java.awt.Dimension(100, 350));
        jPanel5.setLayout(null);

        clear.setBackground(new java.awt.Color(204, 204, 255));
        clear.setText("CLEAR");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel5.add(clear);
        clear.setBounds(20, 90, 90, 30);

        hapus.setBackground(new java.awt.Color(204, 204, 255));
        hapus.setText("DELETE");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        jPanel5.add(hapus);
        hapus.setBounds(20, 190, 90, 30);

        print.setBackground(new java.awt.Color(204, 204, 255));
        print.setText("PRINT");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        jPanel5.add(print);
        print.setBounds(20, 240, 90, 30);

        refresh.setBackground(new java.awt.Color(204, 204, 255));
        refresh.setText("REFRESH");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });
        jPanel5.add(refresh);
        refresh.setBounds(20, 140, 90, 30);

        save.setBackground(new java.awt.Color(204, 204, 255));
        save.setText("SAVE");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel5.add(save);
        save.setBounds(20, 40, 90, 30);

        jPanel1.add(jPanel5);
        jPanel5.setBounds(410, 120, 140, 330);

        akhir.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NomorResi", "NamaPetugas", "NomorPolisi", "JenisKendaraan", "TanggalMasuk", "TanggalKeluar", "HargaPerHari", "TotalPembayaran"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        akhir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                akhirMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(akhir);
        if (akhir.getColumnModel().getColumnCount() > 0) {
            akhir.getColumnModel().getColumn(0).setResizable(false);
            akhir.getColumnModel().getColumn(1).setResizable(false);
            akhir.getColumnModel().getColumn(2).setResizable(false);
            akhir.getColumnModel().getColumn(3).setResizable(false);
            akhir.getColumnModel().getColumn(4).setResizable(false);
            akhir.getColumnModel().getColumn(5).setResizable(false);
            akhir.getColumnModel().getColumn(6).setResizable(false);
            akhir.getColumnModel().getColumn(7).setResizable(false);
        }

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(10, 460, 1030, 120);

        jPanel6.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel6);
        jPanel6.setBounds(560, 120, 480, 330);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1051, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nopolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nopolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nopolActionPerformed

    private void petugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_petugasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_petugasActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd-mm-yyyy");
        String tglmasuk = dateFormat.format(masuk.getDate());
        String tglkeluar = dateFormat.format(keluar.getDate());
        
        Date msk = masuk.getDate();
        Date klr = keluar.getDate();
        long miliseconds = klr.getTime()-msk.getTime();
        int days = (int)miliseconds/(1000*60*60*24);
        int total = days * 3000;
        
        String nomorresi = noresi.getText();
        String namapetugas = petugas.getText();
        String nomorpolisi = nopol.getText();
        String Jenis = "";
            if(motor.isSelected()){Jenis = "motor";}
            else{Jenis="mobil";}
        String hari ="3000";
        
        if(noresi.getText().equals("")||petugas.getText().equals("")||nopol.getText().equals("")||Jenis.equals("")||tglmasuk.equals("")||tglkeluar.equals(""))
        {JOptionPane.showMessageDialog(this,"Harap Lengkapi Data","Error",JOptionPane.WARNING_MESSAGE);}
        else{
            String SQL = "INSERT INTO tb_penitipan (nomor_resi,nama_petugas,nomor_polisi,jenis_kendaraan,tanggal_masuk,tanggal_keluar,hari,total_pembayaran)"
                    +"VALUES('"
                    +noresi.getText()+"','"
                    +petugas.getText()+"','"
                    +nopol.getText()+"','"
                    +Jenis+"','"
                    +tglmasuk+"','"
                    +tglkeluar+"','"
                    +hari+"','"
                    +total+"')";
            int status = KoneksiDB.execute(SQL);
            if(status==1){
                JOptionPane.showMessageDialog(this,"Data Berhasil di update","Sukses",JOptionPane.INFORMATION_MESSAGE);
                refreshData();
            }else
            {
                JOptionPane.showMessageDialog(this,"Data gagal diupdate","Gagal",JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_saveActionPerformed

    private void masukPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_masukPropertyChange
        if(masuk.getDate()!=null){
         SimpleDateFormat simpleDateFormat = 
            new SimpleDateFormat("dd MMMM yyyy");
        tglpinjam = simpleDateFormat.format(masuk.getDate());
        }
    }//GEN-LAST:event_masukPropertyChange

    private void keluarPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_keluarPropertyChange
        if(keluar.getDate()!=null)
        {
            SimpleDateFormat simpleDateFormat = 
            new SimpleDateFormat("dd MMMM yyyy");
            tglkembali = simpleDateFormat.format(keluar.getDate());
        }
    }//GEN-LAST:event_keluarPropertyChange

    private void motorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_motorActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
            refreshData();
    }//GEN-LAST:event_refreshActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        petugas.setText("");
        noresi.setText("");
        nopol.setText("");
        buttonGroup1.clearSelection();
        masuk.setDate(new Date());
        keluar.setDate(new Date());
        
    }//GEN-LAST:event_clearActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        int baris = akhir.getSelectedRow();
        if(baris != -1)
        {
            String NomorResi = akhir.getValueAt(baris, 0).toString();
            String SQL = "DELETE FROM tb_penitipan WHERE nomor_resi='"+NomorResi+"'";
            int status = KoneksiDB.execute(SQL);
            if(status==1)
            {
                JOptionPane.showMessageDialog(this, "Data Berhasil dihapus","Sukses",JOptionPane.INFORMATION_MESSAGE);
            }else
            {
                JOptionPane.showMessageDialog(this, "Data Gagal dihapus","Gagal",JOptionPane.WARNING_MESSAGE);
            }
        }else{JOptionPane.showMessageDialog(this, "PIlih data yang akan dihapus", "Error", JOptionPane.WARNING_MESSAGE);}
    }//GEN-LAST:event_hapusActionPerformed

    private void akhirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_akhirMouseClicked
        int baris = akhir.getSelectedRow();
        if(baris != -1)
        {
            noresi.setText(akhir.getValueAt(baris, 0).toString());
            petugas.setText(akhir.getValueAt(baris, 1).toString());
            nopol.setText(akhir.getValueAt(baris,2).toString());
            if("motor".equals(akhir.getValueAt(baris,3).toString())){motor.setSelected(true);}
            else{mobil.setSelected(true);}
            SimpleDateFormat date = new SimpleDateFormat ("yyyy-MM-dd");
            Date dateFormat = null;
            try {
                dateFormat = date.parse(akhir.getValueAt(baris, 4).toString());
            } catch (ParseException ex) {
                Logger.getLogger(form_pembayaran.class.getName()).log(Level.SEVERE, null, ex);
            }
            masuk.setDate(dateFormat);
            try {
                dateFormat = date.parse(akhir.getValueAt(baris, 5).toString());
            } catch (ParseException ex) {
                Logger.getLogger(form_pembayaran.class.getName()).log(Level.SEVERE, null, ex);
            }
            keluar.setDate(dateFormat);
        }
    }//GEN-LAST:event_akhirMouseClicked

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        MessageFormat header = new MessageFormat("KARTU PARKIR LOUISA GABRIELLA CV");
        MessageFormat footer = new MessageFormat("page {0,number,integer}       ");
        try{
            akhir.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
        }catch (java.awt.print.PrinterException e)
        {
            System.err.format("Cannot print %s%n", e.getMessage());
        }
    }//GEN-LAST:event_printActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_pembayaran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable akhir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton clear;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private com.toedter.calendar.JDateChooser keluar;
    private javax.swing.JLabel labeljam;
    private javax.swing.JLabel labeltanggal;
    private com.toedter.calendar.JDateChooser masuk;
    private javax.swing.JRadioButton mobil;
    private javax.swing.JRadioButton motor;
    private javax.swing.JTextField nopol;
    private javax.swing.JTextField noresi;
    private javax.swing.JTextField petugas;
    private javax.swing.JButton print;
    private javax.swing.JButton refresh;
    private javax.swing.JButton save;
    // End of variables declaration//GEN-END:variables

    private void refreshData() {
        String kolom[] = {"NomorResi","NamaPetugas","NomorPolisi","JenisKendaraan","TanggalMasuk","TanggalKeluar","HargaPerHari","TotalPembayaran"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom);
        String SQL = "SELECT * FROM tb_penitipan";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        try {
            while(rs.next()) {
                String nomor_resi  = rs.getString(1);
                String nama_petugas = rs.getString(2);
                String nomor_polisi = rs.getString(3);
                String jenis_kendaraan = "";
                if ("L".equals(rs.getString(4))){
                    jenis_kendaraan = "motor";
                } else {
                    jenis_kendaraan = "mobil";
                }
                String tanggal_masuk = rs.getString(5);
                String tanggal_keluar = rs.getString(6);
                String hari = rs.getString(7);
                String total_harga = rs.getString(8);
                String data[] = {nomor_resi,nama_petugas,nomor_polisi,jenis_kendaraan,tanggal_masuk,tanggal_keluar,hari,total_harga};
                dtm.addRow(data);
            }
        } catch (SQLException ex){
            Logger.getLogger(form_pembayaran.class.getName()).log(Level.SEVERE, null, ex);
        }
        akhir.setModel(dtm);
    }
}
